from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .controlled_tools import trace_jsonl


def write_outputs(
    output_dir: str | Path,
    graph_id: str,
    findings: list[dict[str, Any]],
    diagnostics: dict[str, Any],
    tool_trace: list[dict[str, Any]],
) -> None:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    final_findings = {"graph_id": graph_id, "schema_version": "0.1", "findings": findings}
    final_answer = {
        "analysis_summary": f"{len(findings)} confirmed finding(s) generated by Scheme A tool-guided analysis.",
        "findings": findings,
        "no_finding_reason": "" if findings else "No chain graph produced a validated finding.",
        "global_uncertainty": "Scheme A findings are limited to controlled tool reads over chain-graph files.",
    }
    (out / "final_findings.json").write_text(json.dumps(final_findings, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "final_answer.json").write_text(json.dumps(final_answer, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "module3A_analysis_diagnostics.json").write_text(json.dumps(diagnostics, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "tool_trace.jsonl").write_text(trace_jsonl(tool_trace), encoding="utf-8")

